Repository chonkie-ai/chonkie, pull requests merged in 2024-11, with the labels that each got.

#29 [BUG] Fix the start_index and end_index to point to character indices, not token indices
  src/chonkie/chunker/sentence.py
  src/chonkie/chunker/token.py
  src/chonkie/chunker/word.py
Labels: bug

#30 [DOCS] Fix typo for import tokenizer in quick start example
  DOCS.md
Labels: documentation

#41 [FEAT] - Add model2vec embedding models
  DOCS.md
  pyproject.toml
  src/chonkie/embeddings/model_2_vec.py
  src/chonkie/embeddings/registry.py
  tests/embeddings/test_model2vec_embeddings.py
Labels: enhancement

#52 [Fix] Token counts from Tokenizers and Transformers adding special tokens
  src/chonkie/chunker/base.py
  tests/chunker/test_token_chunker.py
Labels: enhancement
